name: Build Discussions Leaderboard

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  discussions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: otmane-el-aloi
      REPO_NAME: otmane-el-aloi
      DISCUSSION_CATEGORY_SLUG: advent-2025
      OUTPUT_PATH: public/data/advent/leaderboard.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build leaderboard
        run: |
          node scripts/build_leaderboard.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit leaderboard.json if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update discussions leaderboard"
            git push
          else
            echo "No changes to commit."
          fi
